// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9VY2SNY4_PiKdQ4NaTkxA5Hlw0NzSpM',
    appId: '1:73158557310:web:4e293533c564ad3f5c622f',
    messagingSenderId: '73158557310',
    projectId: 'relgal',
    authDomain: 'relgal.firebaseapp.com',
    storageBucket: 'relgal.appspot.com',
    measurementId: 'G-V5MPRKL74G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOW0i7zevr-DQn6MzBI6Qqa9HX8bC1QNs',
    appId: '1:73158557310:android:858b67b971c0156a5c622f',
    messagingSenderId: '73158557310',
    projectId: 'relgal',
    storageBucket: 'relgal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdbklpHiPr8mxHR_5o9U1Csc4akfhlvmY',
    appId: '1:73158557310:ios:1ada95d5f4958c095c622f',
    messagingSenderId: '73158557310',
    projectId: 'relgal',
    storageBucket: 'relgal.appspot.com',
    iosBundleId: 'com.example.relgal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdbklpHiPr8mxHR_5o9U1Csc4akfhlvmY',
    appId: '1:73158557310:ios:1ada95d5f4958c095c622f',
    messagingSenderId: '73158557310',
    projectId: 'relgal',
    storageBucket: 'relgal.appspot.com',
    iosBundleId: 'com.example.relgal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf9VY2SNY4_PiKdQ4NaTkxA5Hlw0NzSpM',
    appId: '1:73158557310:web:e75505cf38602c015c622f',
    messagingSenderId: '73158557310',
    projectId: 'relgal',
    authDomain: 'relgal.firebaseapp.com',
    storageBucket: 'relgal.appspot.com',
    measurementId: 'G-HM0C646Z2H',
  );
}
